#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := power_measurement
IDF_PATH := ${FIRMWARE_PATH}/components/esp-idf

EXTRA_COMPONENT_DIRS += ${FIRMWARE_PATH}/components/

include ${IDF_PATH}/make/project.mk
